### ISSUE TITLE
Sporadic test failure

### ISSUE THREAD

**Issue by vmx** [pipedown/node-noise#1]
On my machine (Debian) this node-noise test is sometimes failing:

```
test multi concurrent add
    ✓ added a and b
    ✓ added c and d
    ✗ failedError: Index instances still open
      Expected: 
    true
      Actual: 
    false
      Operator: "=="
```

Sometimes the error is:

```
    ✗ failedError: This is an rocksdb error
      Expected: 
    true
      Actual: 
    false
      Operator: "=="
```

**Comment by vmx** [comment]
This one only seems to fail if also another test if failing. If no other test fails, it also doesn't fail.

**Comment by Damienkatz** [comment]
I think I found and fixed the problem. But I've never seen the problem on my machine. See if the issue has gone away with my last commit.

**Comment by vmx** [comment]
Seems to be fixed, I can't reproduce it anymore.
