### ISSUE TITLE
Error on install - Ubuntu - "unresolved import 'neon::js::JsInteger'

### ISSUE THREAD

**Issue by dynamite-ready** [pipedown/node-noise#17]
The full error message is here:

```
Compiling rocksdb v0.8.1
error[E0432]: unresolved import `neon::js::JsInteger`
  --> src/lib.rs:26:32
   |
26 |                Value, JsValue, JsInteger};
   |                                ^^^^^^^^^ no `JsInteger` in `js`

error: aborting due to previous error

error: Could not compile `node-noise`.
```

Do I need to be on a specific version on Node JS? I'm running on 6.10.0.
As for my Rust compiler, I'm running on 1.21.0.

I've had a version of the module running in the recent past, so do wonder if anything has changed.

Thank you.

**Comment by vmx** [comment]
I'm sorry for the long delay. I wasn't properly subscribed to this repository so I didn't get a notification (now I am :)  The good news is that I can reproduce the bug locally, I'm having a look now. Thanks for the bug report.

**Comment by vmx** [comment]
Neon will take care of it. So after https://github.com/neon-bindings/neon/issues/279 is closed, please try to install again.

**Comment by vmx** [comment]
I tried to do a proper fix. So version 0.7.4 should work now. @dynamite-ready can you please try to install/build it again? Thanks.

**Comment by dynamite-ready** [comment]
Just ran a quick install. It looks fine now, thank you.
